name: haoriyangw

on:
  workflow_dispatch:
  schedule:
    - cron: '10 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: haoriyangw
        env:
          jtfy82: ${{ secrets.jtfy82 }}
        run: |
          echo $jtfy82 | jq -r .edmt1 | /bin/bash
          echo $luf5 | jq -r .wu92 | /bin/bash

